all: stack_char stack_double stack_float stack_int stack_long stack_short stack_ptr_to_char stack_ptr_to_double stack_ptr_to_float stack_ptr_to_int stack_ptr_to_long stack_ptr_to_short queue_char queue_double queue_float queue_int queue_long queue_short queue_ptr_to_char queue_ptr_to_double queue_ptr_to_float queue_ptr_to_int queue_ptr_to_long queue_ptr_to_short

stack_char: main_stack_char.o stack_char.o list_char.o mm.o
	gcc -Wall -o stack_char main_stack_char.o stack_char.o list_char.o mm.o
		
stack_double: main_stack_double.o stack_double.o list_double.o mm.o
	gcc -Wall -o stack_double main_stack_double.o stack_double.o list_double.o mm.o
		  
stack_float: main_stack_float.o stack_float.o list_float.o mm.o
	gcc -Wall -o stack_float main_stack_float.o stack_float.o list_float.o mm.o
		 
stack_int: main_stack_int.o stack_int.o list_int.o mm.o
	gcc -Wall -o stack_int main_stack_int.o stack_int.o list_int.o mm.o

stack_long: main_stack_long.o stack_long.o list_long.o mm.o
	gcc -Wall -o stack_long main_stack_long.o stack_long.o list_long.o mm.o

stack_short: main_stack_short.o stack_short.o list_short.o mm.o
	gcc -Wall -o stack_short main_stack_short.o stack_short.o list_short.o mm.o

stack_ptr_to_char: main_stack_ptr_to_char.o stack_ptr_to_char.o list_ptr_to_char.o mm.o
	gcc -Wall -o stack_ptr_to_char main_stack_ptr_to_char.o stack_ptr_to_char.o list_ptr_to_char.o mm.o

stack_ptr_to_double: main_stack_ptr_to_double.o stack_ptr_to_double.o list_ptr_to_double.o mm.o
	gcc -Wall -o stack_ptr_to_double main_stack_ptr_to_double.o stack_ptr_to_double.o list_ptr_to_double.o mm.o

stack_ptr_to_float: main_stack_ptr_to_float.o stack_ptr_to_float.o list_ptr_to_float.o mm.o
	gcc -Wall -o stack_ptr_to_float main_stack_ptr_to_float.o stack_ptr_to_float.o list_ptr_to_float.o mm.o

stack_ptr_to_int: main_stack_ptr_to_int.o stack_ptr_to_int.o list_ptr_to_int.o mm.o
	gcc -Wall -o stack_ptr_to_int main_stack_ptr_to_int.o stack_ptr_to_int.o list_ptr_to_int.o mm.o

stack_ptr_to_long: main_stack_ptr_to_long.o stack_ptr_to_long.o list_ptr_to_long.o mm.o
	gcc -Wall -o stack_ptr_to_long main_stack_ptr_to_long.o stack_ptr_to_long.o list_ptr_to_long.o mm.o
	
stack_ptr_to_short: main_stack_ptr_to_short.o stack_ptr_to_short.o list_ptr_to_short.o mm.o
	gcc -Wall -o stack_ptr_to_short main_stack_ptr_to_short.o stack_ptr_to_short.o list_ptr_to_short.o mm.o

queue_char: main_queue_char.o queue_char.o list_char.o mm.o
	gcc -Wall -o queue_char main_queue_char.o queue_char.o list_char.o mm.o

queue_double: main_queue_double.o queue_double.o list_double.o mm.o
	gcc -Wall -o queue_double main_queue_double.o queue_double.o list_double.o mm.o

queue_float: main_queue_float.o queue_float.o list_float.o mm.o
	gcc -Wall -o queue_float main_queue_float.o queue_float.o list_float.o mm.o

queue_int: main_queue_int.o queue_int.o list_int.o mm.o
	gcc -Wall -o queue_int main_queue_int.o queue_int.o list_int.o mm.o

queue_long: main_queue_long.o queue_long.o list_long.o mm.o
	gcc -Wall -o queue_long main_queue_long.o queue_long.o list_long.o mm.o
		
queue_short: main_queue_short.o queue_short.o list_short.o mm.o
	gcc -Wall -o queue_short main_queue_short.o queue_short.o list_short.o mm.o

queue_ptr_to_char: main_queue_ptr_to_char.o queue_ptr_to_char.o list_ptr_to_char.o mm.o
	gcc -Wall -o queue_ptr_to_char main_queue_ptr_to_char.o queue_ptr_to_char.o list_ptr_to_char.o mm.o

queue_ptr_to_double: main_queue_ptr_to_double.o queue_ptr_to_double.o list_ptr_to_double.o mm.o
	gcc -Wall -o queue_ptr_to_double main_queue_ptr_to_double.o queue_ptr_to_double.o list_ptr_to_double.o mm.o

queue_ptr_to_float: main_queue_ptr_to_float.o queue_ptr_to_float.o list_ptr_to_float.o mm.o
	gcc -Wall -o queue_ptr_to_float main_queue_ptr_to_float.o queue_ptr_to_float.o list_ptr_to_float.o mm.o

queue_ptr_to_int: main_queue_ptr_to_int.o queue_ptr_to_int.o list_ptr_to_int.o mm.o
	gcc -Wall -o queue_ptr_to_int main_queue_ptr_to_int.o queue_ptr_to_int.o list_ptr_to_int.o mm.o

queue_ptr_to_long: main_queue_ptr_to_long.o queue_ptr_to_long.o list_ptr_to_long.o mm.o
	gcc -Wall -o queue_ptr_to_long main_queue_ptr_to_long.o queue_ptr_to_long.o list_ptr_to_long.o mm.o
	
queue_ptr_to_short: main_queue_ptr_to_short.o queue_ptr_to_short.o list_ptr_to_short.o mm.o
	gcc -Wall -o queue_ptr_to_short main_queue_ptr_to_short.o queue_ptr_to_short.o list_ptr_to_short.o mm.o

main_stack_char.o:
	gcc -Wall -c main_stack_char.c

main_stack_double.o:
	gcc -Wall -c main_stack_double.c

main_stack_float.o:
	gcc -Wall -c main_stack_float.c

main_stack_int.o:
	gcc -Wall -c main_stack_int.c

main_stack_long.o:
	gcc -Wall -c main_stack_long.c
		   
main_stack_short.o:
	gcc -Wall -c main_stack_short.c

main_stack_ptr_to_char.o:
	gcc -Wall -c main_stack_ptr_to_char.c
	
main_stack_ptr_to_double.o:
	gcc -Wall -c main_stack_ptr_to_double.c

main_stack_ptr_to_float.o:
	gcc -Wall -c main_stack_ptr_to_float.c

main_stack_ptr_to_int.o:
	gcc -Wall -c main_stack_ptr_to_int.c

main_stack_ptr_to_long.o:
	gcc -Wall -c main_stack_ptr_to_long.c
	
main_stack_ptr_to_short.o:
	gcc -Wall -c main_stack_ptr_to_short.c

main_queue_char.o:
	gcc -Wall -c main_queue_char.c

main_queue_double.o:
	gcc -Wall -c main_queue_double.c

main_queue_float.o:
	gcc -Wall -c main_queue_float.c

main_queue_int.o:
	gcc -Wall -c main_queue_int.c

main_queue_long.o:
	gcc -Wall -c main_queue_long.c
	
main_queue_short.o:
	gcc -Wall -c main_queue_short.c

main_queue_ptr_to_char.o:
	gcc -Wall -c main_queue_ptr_to_char.c

main_queue_ptr_to_double.o:
	gcc -Wall -c main_queue_ptr_to_double.c

main_queue_ptr_to_float.o:
	gcc -Wall -c main_queue_ptr_to_float.c

main_queue_ptr_to_int.o:
	gcc -Wall -c main_queue_ptr_to_int.c

main_queue_ptr_to_long.o:
	gcc -Wall -c main_queue_ptr_to_long.c
	
main_queue_ptr_to_short.o:
	gcc -Wall -c main_queue_ptr_to_short.c

stack_char.o:
	gcc -Wall -c stack_char.c

stack_double.o:
	gcc -Wall -c stack_double.c
	
stack_float.o:
	gcc -Wall -c stack_float.c

stack_int.o:
	gcc -Wall -c stack_int.c

stack_long.o:
	gcc -Wall -c stack_long.c
	
stack_short.o:
	gcc -Wall -c stack_short.c

stack_ptr_to_char.o:
	gcc -Wall -c stack_ptr_to_char.c

stack_ptr_to_double.o:
	gcc -Wall -c stack_ptr_to_double.c

stack_ptr_to_float.o:
	gcc -Wall -c stack_ptr_to_float.c

stack_ptr_to_int.o:
	gcc -Wall -c stack_ptr_to_int.c

stack_ptr_to_long.o:
	gcc -Wall -c stack_ptr_to_long.c
	
stack_ptr_to_short.o:
	gcc -Wall -c stack_ptr_to_short.c

queue_char.o:
	gcc -Wall -c queue_char.c

queue_double.o:
	gcc -Wall -c queue_double.c
	
queue_float.o:
	gcc -Wall -c queue_float.c
	
queue_int.o:
	gcc -Wall -c queue_int.c

queue_long.o:
	gcc -Wall -c queue_long.c
	
queue_short.o:
	gcc -Wall -c queue_short.c

queue_ptr_to_char.o:
	gcc -Wall -c queue_ptr_to_char.c
	
queue_ptr_to_double.o:
	gcc -Wall -c queue_ptr_to_double.c

queue_ptr_to_float.o:
	gcc -Wall -c queue_ptr_to_float.c

queue_ptr_to_int.o:
	gcc -Wall -c queue_ptr_to_int.c

queue_ptr_to_long.o:
	gcc -Wall -c queue_ptr_to_long.c
	
queue_ptr_to_short.o:
	gcc -Wall -c queue_ptr_to_short.c

list_char.o:
	gcc -Wall -c list_char.c

list_double.o:
	gcc -Wall -c list_double.c

list_float.o:
	gcc -Wall -c list_float.c
	
list_int.o:
	gcc -Wall -c list_int.c

list_long.o:
	gcc -Wall -c list_long.c
	
list_short.o:
	gcc -Wall -c list_short.c

list_ptr_to_char.o:
	gcc -Wall -c list_ptr_to_char.c

list_ptr_to_double.o:
	gcc -Wall -c list_ptr_to_double.c

list_ptr_to_float.o:
	gcc -Wall -c list_ptr_to_float.c
	
list_ptr_to_int.o:
	gcc -Wall -c list_ptr_to_int.c

list_ptr_to_long.o:
	gcc -Wall -c list_ptr_to_long.c
	
list_ptr_to_short.o:
	gcc -Wall -c list_ptr_to_short.c

mm.o:
	gcc -Wall -c mm.c

dep:
	gcc -M *.c > .depend

clean:
	rm -f .depend stack_char stack_double stack_float stack_int stack_long stack_short stack_ptr_to_char stack_ptr_to_double stack_ptr_to_float stack_ptr_to_int stack_ptr_to_long stack_ptr_to_short queue_char queue_double queue_float queue_int queue_long queue_short queue_ptr_to_char queue_ptr_to_double queue_ptr_to_float queue_ptr_to_int queue_ptr_to_long queue_ptr_to_short  *.o *~*.*~
